### ISSUE TITLE
Error displaying a quote

### ISSUE THREAD

**Issue by tecnoborder** [decatetsu/local-quotes#20]
Starting from today, the quote I have in my home page does not show (always, sometimes it does) correctly
<img width="547" alt="Screen Shot 2022-07-28 at 13 55 36" src="https://user-images.githubusercontent.com/18950662/181499497-86364763-4c43-4d2d-8dba-9ca8f18cc816.png">

**Comment by tecnoborder** [comment]
<img width="439" alt="Screen Shot 2022-07-28 at 13 55 41" src="https://user-images.githubusercontent.com/18950662/181499555-5210903a-5f9f-461d-ab25-8ba075c5abab.png">

**Comment by ka1tzyu** [comment]
Is this console error and Local Quotes' message ("You caught an error...") show up in the same time?

**Comment by tecnoborder** [comment]
<img width="544" alt="Screen Shot 2022-07-28 at 19 29 48" src="https://user-images.githubusercontent.com/18950662/181602678-fd25bc11-032a-4f6a-8983-3df8241dba48.png">
<img width="542" alt="Screen Shot 2022-07-28 at 19 29 27" src="https://user-images.githubusercontent.com/18950662/181602701-83a3951b-9844-4aba-a0a0-31bbc7af1d01.png">

**Comment by tecnoborder** [comment]
nothing specific to local notes.

**Comment by ka1tzyu** [comment]
Try to clear block metadata and one-time block metadata in the Local Quotes settings. It's placed in a "Danger Zone". It'll clear cached metadata. Then you should relaunch app. It must help. If it's not help, write me back.

**Comment by tecnoborder** [comment]
I did so and relaunched the app. Unforuntalt the issue is still present

**Comment by ka1tzyu** [comment]
Do you create this quote block via Quote Maker or by typing code block by yourself?

**Comment by tecnoborder** [comment]
the quote maker. I found this problem happening when I use the workspace feature of obsidian to lead the home page. I have a home page note with an inserted quote.

**Comment by ka1tzyu** [comment]
I tried to reproduce it with workspaces and all work correctly. Can you share a sample vault with the problem?

**Comment by tecnoborder** [comment]
The issue does not happen always. I will investigate further!

**Comment by ka1tzyu** [comment]
I'll be waiting for the results of your investigation

**Comment by tecnoborder** [comment]
<img width="467" alt="Screen Shot 2022-07-30 at 10 59 14" src="https://user-images.githubusercontent.com/18950662/181903286-bdc82f01-a9dc-410c-bef0-12f25a564c53.png">

**Comment by tecnoborder** [comment]
Could it be a problem with the load of dataview?

**Comment by tecnoborder** [comment]
<img width="464" alt="Screen Shot 2022-07-30 at 11 33 34" src="https://user-images.githubusercontent.com/18950662/181904522-d07df057-0e71-40d9-9893-f351f7e38dac.png">

**Comment by tecnoborder** [comment]
when I click on the refresh button

**Comment by ka1tzyu** [comment]
> <img alt="Screen Shot 2022-07-30 at 10 59 14" width="467" src="https://user-images.githubusercontent.com/18950662/181903286-bdc82f01-a9dc-410c-bef0-12f25a564c53.png">

It is just info message


> Could it be a problem with the load of dataview?

I don't think so, but previously I caught and fixed some conflicts with the dataview

**Comment by ka1tzyu** [comment]
Can you send me a code block that provoke an issue? You can replace private parts (e.g. author) if it's necessary

**Comment by tecnoborder** [comment]
:::This is the author:::
- 1) This is a quote:
	This is a sub-quote
- 2) This is the second quote:
	This is another sub-quote

**Comment by tecnoborder** [comment]
```localquote
id aZn3k
search This is the author
refresh 1d
```

**Comment by ka1tzyu** [comment]
There is nothing suspicious. You said it works sometimes?

**Comment by ka1tzyu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Error displaying a quote](https://trello.com/c/xAMG9cUU/1-error-displaying-a-quote)

**Comment by tecnoborder** [comment]
Yes, I can confirm the bug is still present 
<img width="556" alt="Screenshot 2022-09-16 at 18 23 50" src="https://user-images.githubusercontent.com/18950662/190685547-4fb940de-ca59-4b27-81ab-d1f7e9bb73a8.png">

**Comment by decatetsu** [comment]
This issue should be fixed with the latest commits. The update will be shipped today!
