### ISSUE TITLE
One Time Quotes are only being pulled from one note

### ISSUE THREAD

**Issue by aarotaylor** [decatetsu/local-quotes#22]
**Describe the bug**
One Time Quotes being used in a daily template are only being pulled from one file despite multiple files having the "quote" tag within them

**To Reproduce**
I have a single template in a dedicated folder, with a one time quote template and "search *" being the only thing in the localquote-once creation block

```localquote-once
search *
```

**Expected behavior**
Quotes should be pulled from all files that have the quotes tag and are formatted correctly

**Screenshots**
Data.json, only Chapterhouse Dune.md has its quotes pulled
![data.json](https://user-images.githubusercontent.com/60279223/195740867-792ac71f-4652-4fbe-bf16-d531e9717c38.jpg)

Chapterhouse Dune.md
![File 0, only quote file included](https://user-images.githubusercontent.com/60279223/195741013-68a3b230-c5b3-4c79-964e-864adc1037e2.JPG)

The two subsequent pics are from two different files, both have the quotes tag
![File1 example, not included](https://user-images.githubusercontent.com/60279223/195740903-d226695b-d002-420f-815d-add68b582de5.JPG)
![File2 example, not included](https://user-images.githubusercontent.com/60279223/195740948-5a53c2de-e9c7-4a88-9807-4cf80520df9c.JPG)

---

Template view

![blankquote](https://user-images.githubusercontent.com/60279223/195742078-6d188836-a58e-4f11-8bbe-c6be5b6366ee.JPG)

![blankquote1](https://user-images.githubusercontent.com/60279223/195742102-0bef7186-729b-4c1f-bdf0-dec85cc05781.JPG)

![blankquote2](https://user-images.githubusercontent.com/60279223/195742109-7593f460-b41e-4145-8dc1-3874344d9989.JPG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Obsidian version: 1, but this bug was present in the previous version

**Additional context**
I've tried reinstalling the plugin, clearing and re-clearing cache, scanning the vault, even deleting the data.json file. Only one of the files that contains the quotes is ever put into rotation

**Comment by decatetsu** [comment]
Thank you for your feedback! I'm going to completely refactor a plugin soon, and these changes should fix this bug. I can't set an approximate update date, because of a lot of work. But I think it'll be done until this month.

**Comment by decatetsu** [comment]
@aarotaylor A lot of time passed, and I returned to maintaining plugin. May you send me a copy of problematic files?

**Comment by aarotaylor** [comment]
@decatetsu strangely the issue seems to have fixed itself. Since my initial post I collected all the quotes in one file with the "#quotes" tag at the bottom. When I added the quotes tag to another file then rescanned the new quotes were added to the vault just fine. 

Not sure what I was doing wrong in the initial post, but the issue appears resolved.
