### ISSUE TITLE
[BUG] Refresh button does not show

### ISSUE THREAD

**Issue by OmniNaut** [decatetsu/local-quotes#23]
The refresh button is not visible when in reading or live preview mode. It does not show when the mouse is clicking or hovering or outside the block
When i hover over the block in the live preview mode, I see in the top right the edit this block icon, but no refresh button.

Code I use:
```
localquote
id 1
search *
refresh 1s
````

![image](https://user-images.githubusercontent.com/110312864/221322718-e71ee896-6f40-4773-a65c-0e27f8764680.png)
![image](https://user-images.githubusercontent.com/110312864/221322808-0bc80f68-bf0d-4efa-bf16-4786a2b578dc.png)

I use Obsidian 1.1.15
I see no related issues in the console

**Comment by decatetsu** [comment]
> When i hover over the block in the live preview mode, I see in the top right the edit this block icon, but no refresh button.

With **Style Settings** plugin, you can select a corner of the refresh button. It should be visible while hovering a block. Try to change the corner.

**Comment by OmniNaut** [comment]
![image](https://user-images.githubusercontent.com/110312864/221355381-fab1b50a-3543-441a-8944-0540e935f77c.png)
Already tried that option, same result. No refresh button shows up

**Comment by decatetsu** [comment]
Got it. I'll look into this. Issue will be solved as soon as possible

**Comment by decatetsu** [comment]
@OmniNaut  Update plugin to the latest version (1.8.5). Issue is resolved, I suppose

**Comment by OmniNaut** [comment]
I checked with update in Obisidian, it claims no update was found. 1.8.4 is still the latest one. Also checked with BRAT, also no update

**Comment by decatetsu** [comment]
@OmniNaut Update was delivered earlier. Try to install from community plugins. If this error persist, send here a code block that provokes it

**Comment by OmniNaut** [comment]
The original install, was from the community plugins, the BRAT and manual install I only did because it wouldn't update. 
Now I removed the plugin and reinstalled it. But still 1.8.4 is installed. Not 1.8.5

**Comment by OmniNaut** [comment]
I solved the problem of the error, that one was on my side.
I have manually deleted the plugin, downloaded the release files and put them in the plugins folder myself. Because the community plugins still say 1.8.4
![image](https://user-images.githubusercontent.com/110312864/221403160-b10ce769-8f46-4761-b65a-cfc1b2d7bb12.png)

With 1.8.5 I have a refresh button and it works in a note, so 👍🏼.
However having that note on a canvas will not refresh.
When I click in the note on the canvas the quote is updated. When I click out of the note, on a different part of the canvas. The old quote is shown again.
I don't know if it's a bug from the plugin or from Canvas

**Comment by decatetsu** [comment]
@OmniNaut Canvas really can provoke some errors because Local Quotes is not adapted for this feature yet, I will look into it after huge codebase update (with some new features). About update, something strange with GitHub caching is happening, community page says it was updated 21 hours ago (exactly when 1.8.5 was released), but actual version is 1.8.4. I will close this issue as resolved and will open a new one about canvas support.

**Comment by decatetsu** [comment]
@OmniNaut Update is already on community plugins page!
