### ISSUE TITLE
[FEATURE REQUEST] Auto refresh without reopening

### ISSUE THREAD

**Issue by OmniNaut** [decatetsu/local-quotes#25]
**Describe the bug**
My understanding of the refresh argument within the code is that every X second/minutes/hours/days a new quote is loaded automatically. Somehow this does not work for me. 
When I'm in live preview or reading mode, the only way to (auto) refresh is to click the edit code block button, and then click out of it again or close and reopen the note.

**To Reproduce**
Steps to reproduce the behaviour:
1. Code block used:
```localquote
id 1
search *
refresh 5s
```
![image](https://user-images.githubusercontent.com/110312864/221430676-e083d532-2bd5-477f-a450-26b2b6359a0a.png)
2. After 5 seconds it's still the same.
4. Click edit this block
5. Click outside of the code block
6. Only now the quote is refreshed
![image](https://user-images.githubusercontent.com/110312864/221430816-80de24d3-471e-447f-80c3-22eb2c6361e8.png)

**Expected behaviour**
Quotes are refreshed automatically (without any user input) refreshed within the given time interval.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11 22H2
 - Obsidian version 1.1.15

**Additional context**

**Comment by decatetsu** [comment]
It can refresh only after note reopen. After each opening, it checks whether refresh time is elapsed or not. So, actually, it's not a bug. But I can add it to the roadmap if you want this kind of refresh behavior.

**Comment by OmniNaut** [comment]
Yes as a new feature will be awesome. 
I use this plugin more in a dashboard setting, so auto refresh without reopening will be 👍🏼

**Comment by OmniNaut** [comment]
Hi @decatetsu,

Any follow up on this request?

**Comment by decatetsu** [comment]
Hello, @OmniNaut. I have to finish my exams these weeks, immediately after that I will start updating the plugin. I need to rewrite some components to fix issues with canvas, plus auto-refresh feature involves some rewriting.

**Comment by decatetsu** [comment]
Development was abandoned for a bit because of my university tasks, sorry for waiting

**Comment by OmniNaut** [comment]
@decatetsu 
Don't worry, I was just checking in. 
University and exams have a higher priority, good luck the next weeks.

**Comment by decatetsu** [comment]
@OmniNaut I'm happy to introduce you to automatic quote refreshing in the latest version ([1.9.0](https://github.com/decatetsu/local-quotes/releases/tag/1.9.0))

**Comment by OmniNaut** [comment]
Awesome, thank you so much. Works as expected.
