### ISSUE TITLE
BUG: Local quotes no longer working

### ISSUE THREAD

**Issue by tecnoborder** [decatetsu/local-quotes#26]
Local quotes no longer works on the latest obsidian insider build
<img width="550" alt="Screenshot 2023-07-11 at 15 42 02" src="https://github.com/decatetsu/local-quotes/assets/18950662/ffde2ab7-2c04-42a2-b71b-4f072b45681a">

**Comment by decatetsu** [comment]
Thank you for noticing. I have no free time and can't promise soon update, but it will be fixed

**Comment by tecnoborder** [comment]
it works, thanks a lot!!
